Add extract-text-webpack-plugin-steamer
使用时项目报错找不到 `extract-text-webpack-plugin-steamer`，补充到 package.json 上去。同时删除项目里没有用到的 extract-text-webpack-plugin 第三方库。
```shell
yarn run v0.21.3
$ npm start

> steamer-react-component@1.0.0 start /Users/steven.yu/github/steamer-react-component
> node ./tools/start.js

module.js:341
    throw err;
    ^

Error: Cannot find module 'extract-text-webpack-plugin-steamer'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/steven.yu/github/steamer-react-component/tools/webpack.example.js:12:25)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/steven.yu/github/steamer-react-component/tools/webpack.server.js:9:21)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! steamer-react-component@1.0.0 start: `node ./tools/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the steamer-react-component@1.0.0 start script 'node ./tools/start.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the steamer-react-component package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./tools/start.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs steamer-react-component
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls steamer-react-component
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/steven.yu/github/steamer-react-component/npm-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```